### NumPy: Introdução

NumPy é uma biblioteca fundamental para computação científica em Python. Ela fornece suporte para arrays multidimensionais e funções matemáticas de alto desempenho para manipulação desses arrays.

Nesta seção, veremos exemplos básicos de:

- Criação de arrays
- Operações aritméticas com arrays
- Indexação e fatiamento de arrays
- Funções matemáticas universais (ufuncs)
- Agregação e estatísticas básicas

---


#### 1. Criação de Arrays

In [1]:
import numpy as np

# Criar um array 1D
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

# Criar um array 2D
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)

[1 2 3 4]
[[1 2]
 [3 4]]



#### 2. Operações Aritméticas com Arrays

In [2]:
# Operações elementares
arr = np.array([1, 2, 3, 4])
arr + 1  # Soma de 1 a cada elemento
arr * 2  # Multiplicação de cada elemento por 2


array([2, 4, 6, 8])

#### 3. Indexação e Fatiamento de Arrays


In [3]:
# Indexação
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Primeiro elemento

# Fatiamento
print(arr[1:4])  # Elementos do índice 1 ao 3


10
[20 30 40]


#### 4. Funções Matemáticas Universais (ufuncs)

In [4]:
# Funções matemáticas
arr = np.array([1, 2, 3, 4])

# Seno de cada elemento
print(np.sin(arr))

# Exponenciação de cada elemento
print(np.exp(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


#### 5. Agregação e Estatísticas Básicas

In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Soma
print(np.sum(arr))

# Média
print(np.mean(arr))

# Desvio padrão
print(np.std(arr))

# Valor máximo
print(np.max(arr))


15
3.0
1.4142135623730951
5
